### ISSUE TITLE
Изменение переменной во множестве веток тяжело анализировать

### ISSUE THREAD

**Issue by AlphaBeth** [SamBridgess/prog_lab5_java8#4]
https://github.com/SamBridgess/prog_lab5_java8/blob/8b06216d06326bf4cd5468ec3407d34f5a2e4ccf/lab5/lab-client/src/main/java/ilya/lab/client/Classes/Route.java#L123-L148

Лучше организуйте код так, чтобы результат сравнения возвращался сразу же, когда он станет очевидным. Например
```
        if (this.distance > r.getDistance()) {
            return 1;
        }
```
Это упростит понимание и избавит код от лишних проверок (например, не нужно будет сравнение `this.distance == r.getDistance()`).

**Comment by SamBridgess** [comment]
fixed
