### ISSUE TITLE
Файлы не закрываются в случае ошибки/после завершения работы с ними

### ISSUE THREAD

**Issue by AlphaBeth** [SamBridgess/prog_lab5_java8#5]
https://github.com/SamBridgess/prog_lab5_java8/blob/8b06216d06326bf4cd5468ec3407d34f5a2e4ccf/lab5/lab-client/src/main/java/ilya/lab/client/Commands/ExecuteScriptCommand.java#L43-L69

**Comment by SamBridgess** [comment]
fixed
